### PR TITLE
remove axios

### PR DESCRIPTION
**Pull request by dcoellarb**
regular js fetch should be enough

### CODE REVIEW

**Comment by drandx** [comment]
Nice. Can you update the README file we will not use axio anymore.

**Comment by dcoellarb** [comment]
sure

**Comment by jeanpierrevg** [comment]
We are just missing the sample right?

**Comment by dcoellarb** [comment]
@jeanpierrevg yes waiting for the network layer from @drandx this PR is not completed yet

**Comment by jeanpierrevg** [comment]
We also need to remove Axios from Dependencies used at Tangocode section in the home page

**Comment by dcoellarb** [comment]
@jeanpierrevg it is removed from the readme, but just in this PR so far, so if you go to the branch dc1 you wont see it

**Pull request merged**
